site_name: Sprinter's Homelab (WIP)
site_author: Sprinter05
repo_url: https://github.com/Sprinter05/homelab
repo_name: Sprinter05/homelab
copyright: Copyright &copy; 2026 Sprinter05

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - autorefs
  - glightbox

theme:
  name: material
  language: en
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/github

  features:
    - header.autohide
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
    - toc.follow
    - search.suggest
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # Light mode
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # Dark mode
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Home: index.md
  - Systems:
      - OrangePI: systems/orangepi.md
      - VPS: systems/vps.md
