site_name: Sprinter's Homelab (WIP)
site_author: Sprinter05
repo_url: https://github.com/Sprinter05/homelab
repo_name: Sprinter05/homelab
copyright: Copyright &copy; 2026 Sprinter05

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - autorefs
  - glightbox

theme:
  name: material
  language: en
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/github

  features:
    - header.autohide
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
    - toc.follow
    - search.suggest
    - search.highlight

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # Light mode
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # Dark mode
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Home: index.md
  - Systems:
      - OrangePI: systems/orangepi.md
      - VPS: systems/vps.md
  - Services:
      - Authelia: services/authelia.md
      - Traefik: services/traefik.md
      - PiHole: services/pihole.md
      - Homepage: services/homepage.md
      - Dozzle: services/dozzle.md
      - Wireguard Easy: services/wg-easy.md
      - Dashdot: services/dashdot.md
      - Glances: services/glances.md
      - Grafana: services/grafana.md
      - PeaNUT: services/peanut.md
      - Syncthing: services/syncthing.md
      - Mailcow: services/mailcow.md
      - Immich: services/immich.md
      - Navidrome: services/navidrome.md
      - Vikunja: services/vikunja.md
      - Mealie: services/mealie.md
      - Jellyfin: services/jellyfin.md
      - FreshRSS: services/freshrss.md
      - Filebrowser Quantum: services/quantum.md
      - Forgejo: services/forgejo.md
      - Minecraft: services/minecraft.md
      - ZNC: services/znc.md
  - Miscellaneous:
      - Domains: misc/domains.md
      - Scripts: misc/scripts.md
      - Router: misc/router.md
  - Failed Projects:
      - DIY NAS: failed/diy_nas.md
